package reality;

public enum EventType {

	JOB_COMPLETED, TERMINATE_RESOURCE_IF_IDLING, TASK_LAST_START_TIME_EXCEEDED, WORKFLOW_COMPLETED
//	JOB_COMPLETION_THRESHOLD_EXCEEDED, 
	//CHECK_UNUNSED_CAPACITY_ON_COMPLETED_RESOURCE
	
	
	
}
